version: '3.8'

services:
  app:
    image: my-spring-boot-app:latest
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
      - redis

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
