
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: pappy
      MYSQL_PASSWORD: pappy
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3310:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

