services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: pappy
      POSTGRES_PASSWORD: pappy
    ports:
      - "3310:5432"

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"


