spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/mydb
    username: pappy
    password: pappy

  data:
    redis:
      host: redis
      port: 6379

  jpa:
    hibernate:
      ddl-auto: none
