spring:
  profiles:
    active: dev

  config:
    import: optional:file:.env[.properties]

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  jwt:
    secret: ${secret_key}

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG
