spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3310/mydb
    username: pappy
    password: pappy

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  jwt:
    secret: U9J3fWm0gVd6K1nX8Qc4TpL7Rs2AvB5oZhYiN0CkJqDxWElMF3OyPGHtRaVX7MBKe



logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG # Apache HTTP 클라이언트를 사용하는 경우